version: '3.3'

networks:
  monitor-net:
    driver: bridge
  monitor-net-one:
    driver: bridge
  monitor-net-too:
    driver: bridge
  monitor-net-main:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
      - monitor-net-one
      - monitor-net-too
      - monitor-net-main
    labels:
      org.label-schema.group: "monitoring"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "montest"
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_USER}
    expose:
      - 5432
    networks:
      - monitor-net-one
      
  redis:
    image: redis
    networks:
      - monitor-net-too
    expose:
      - 6379

  nginx:
    image: nginx
    container_name: nginx
    volumes:
     - ./mon.nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - grafana
    ports:
      - "80:80" 
      - "8080:80"
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
      - "5432:5432"
    restart: unless-stopped
    networks:
      - monitor-net-main
    labels:
      org.label-schema.group: "monitoring"

