apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    
datasources:
  - name: postgres
    type: postgres
    access: proxy
    orgId: 1
    url: http://postgres:5432
    basicAuth: false
    isDefault: true
    editable: true
    
datasources:
  - name: redis
    type: redis
    access: proxy
    orgId: 1
    url: http://redis:6379
    basicAuth: false
    isDefault: true
    editable: true