apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    orgId: 1
    url: postgres:5432
    database: montest
    user: admin
    secureJsonData:
      password: 'Qwerta123!!!' 
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0 
      maxIdleConns: 2 
      connMaxLifetime: 14400
      postgresVersion: 1400 
      timescaledb: false